# This will run on merging new Features into develop and Prepering commits for merges into master.

name: Upcoming Release CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup VSTest.console.exe
        uses: darenm/Setup-VSTest@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore ArcDPS-Updater.sln

      # Build the Solution with the configuration Release
      - name: Build the Solution
        run: msbuild -r -t:Rebuild ArcDPS-Updater.sln /p:Configuration=Release

      - name: Run Unittests
        run: vstest.console.exe "ArcDPS-Updater-Tests\bin\Release\netcoreapp3.1\ArcDPS-Updater-Tests.dll"
        
      # Collect the build results
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
            name: buildResult
            path: ArcDPS-Updater/bin/Release/netcoreapp3.1/
